### ISSUE TITLE
O valor `Transaction Amount` para o EMV `null` é invalido: Required.

### ISSUE THREAD

**Issue by NadsonKT** [piggly-dev/php-pix#22]
Existe um pequeno problema na classe "StaticPayload", a linha 34 define a EMV 54 (Transaction Amount) como requerida, porém isso é um pouco contraditório a documentação, onde diz que a função "setAmount" é opcional.

Uma solução encontrada foi chamar o método changeMpm da classe StaticPayload, passando a instância da classe MPM como parâmetro. Segue o código abaixo.

``` php
use Piggly\Pix\StaticPayload;
use Piggly\Pix\Emv\MPM;

$payload = (new StaticPayload())
	->changeMpm(new MPM) // ADD
	->setPixKey($keyType, $keyValue)
	->setMerchantName($merchantName)
	->setMerchantCity($merchantCity)
	//->setAmount($amount)
	->setTid($tid)
	->setDescription($description);

```

**Comment by caiquearaujo** [comment]
Corrigido na versão 2.0.2
