### ISSUE TITLE
TRUNCADO no BB

### ISSUE THREAD

**Issue by leuuuuu** [piggly-dev/php-pix#24]
Estou gerando QR-Code estático, testei em 3 brancos e funcionou normal, no Banco do Brasil da erro

**Comment by caiquearaujo** [comment]
Por favor, compartilhe o erro para identificarmos o problema.

**Comment by leuuuuu** [comment]
Parâmetros inválidos (010-010_ (000-000)

**Comment by caiquearaujo** [comment]
@leuuuuu acredito que tenha sido solucionado.
