### ISSUE TITLE
Código de retorno

### ISSUE THREAD

**Issue by otaviobarreto** [piggly-dev/php-pix#26]
Olá estou buscando uma solução para saber automaticamente quando o pagamento do pix foi concluído, alguém já conseguiu qual código de retorno tratar?

**Comment by kozfelipe** [comment]
Oi, possuo a mesma dúvida. Este projeto trata a leitura de status de pagamento ou somente gera o QR Code? Eu precisaria de um cadastro especial junto ao banco? desde já agradeço.

**Comment by caiquearaujo** [comment]
Olá, @kozfelipe e @otaviobarreto, esse código apenas gera o QR Code e o código Pix seguindo o padrão EMV, ele normaliza os dados por tanto. Para implementação da leitura do status de pagamento, você deve:

1. Solicitar ao banco do titular acesso a API do Pix;
2. Implementar a conexão com a API do Pix desejada;
3. Desenvolver o código para tratar a leitura do status do pagamento.
