### ISSUE TITLE
Cronjob não atualiza o status do pix dinâmico

### ISSUE THREAD

**Issue by juniorenato** [piggly-dev/php-pix#27]
Oi, implementei a API Pix do PagSeguro e quando clico no botão processar agora ele atualiza o status normalmente, mas quando eu espero que o Cronjob faça automaticamente o plugin não atualiza o status. Eu verifiquei os logs de acesso e com uma série de testes identifiquei que o meu script é acessado normalmente, mas mesmo assim não atualiza o status.

Uma informação importante é que mesmo retornando a classe `DynamicPayload` dentro do filtrer `pgly_wc_piggly_pix_payload` o plugin continua tratando o pix como estático,  contornei isso deixando de verificar pelo método `getType()` e analisando a string retornada pelo método `getBrCode()`.

**Comment by juniorenato** [comment]
Identifiquei o problema da verificação automática, porém ao gerar o Pix dinâmico o sistema não identifica, fazendo com que o pedido seja tratado como Pix estático.

**Comment by caiquearaujo** [comment]
Você está solicitando suporte para o plugin Pix por Piggly, outro código que não esse. Mas, vou auxiliar de todo modo:

1. O filtro `pgly_wc_piggly_pix_payload` deve retornar o payload DynamicPayload, está correto;
2. Entretanto, se você não implementar a ação `pgly_wc_piggly_pix_process` para processar esse payload Dinâmico via API, não vai funcionar, é preciso que você faça o gatilho de processamento.
