### ISSUE TITLE
[Sicoob] QR Code expirado, entre em contato com o recebedor.

### ISSUE THREAD

**Issue by lucasrodrigobento** [piggly-dev/php-pix#28]
Através do aplicativo do NuBank, consegui realizar a leitura do QR Code normalmente. Mas, através do aplicativo do banco Sicoob a seguinte mensagem é exibida:

> QR Code expirado, entre em contato com o recebedor.

Obs.: O QR Code está sendo gerado a partir de uma SPI URL (do banco recebedor - Bradesco).

**Pix Copia e Cola** do referido **QR Code**:

`00020101021226970014br.gov.bcb.pix2575qrpix.bradesco.com.br/qr/v2/cobv/bdf3c8-05fa26e0c-9e4fe2bff1ab5421d37a6d3175204000053039865802BR5925ILEVA GESTAO INTELIGENTE 6007GOIANIA62070503***63040130`

![1](https://user-images.githubusercontent.com/11876716/182156943-2538af4b-e582-4dce-8dac-1f400ab56d4a.png)

**Comment by caiquearaujo** [comment]
Você está utilizando um QR Code emitido dinamicamente, nesse caso o problema é na emissão do Pix na API no banco do Bradesco. Provavelmente está sendo criado uma cobrança com vencimento ou com calendário. Nosso código apenas cria o código Pix.

**Comment by lucasrodrigobento** [comment]
> Você está utilizando um QR Code emitido dinamicamente, nesse caso o problema é na emissão do Pix na API no banco do Bradesco. Provavelmente está sendo criado uma cobrança com vencimento ou com calendário. Nosso código apenas cria o código Pix.

Realmente o problema está vinculado à forma com que o aplicativo de leitura processa a URL de Payload do QR Code.
