### ISSUE TITLE
Retorno/liberação automática para produtos baixáveis

### ISSUE THREAD

**Issue by kandayss** [piggly-dev/php-pix#29]
Como implementar está função pelo Pagseguro ou Nubank? Obrigado desde já.

**Comment by kandayss** [comment]
.

**Comment by alkabane** [comment]
up

**Comment by caiquearaujo** [comment]
@kandayss esse repositório apenas monta os QR Code e possuí as entidades de uma API Pix. Mas você precisa fazer a integração com a API do seu banco. Cada banco tem uma API própria. Que eu saiba o Nubank não tem API.
