### ISSUE TITLE
Este repositório ainda está sendo mantido?

### ISSUE THREAD

**Issue by paulovitorbal** [piggly-dev/php-pix#33]
Verificando as issues abertas e o pull request aberto fiquei com a impressão que esté repositório está abandonado.

Se sim, seria possível passar ele pra algum mantenedor que esteja disposto a dar continuidade ao desenvolvimento deste pacote?

Se for o caso, eu me coloco a disposição para manter o pacote.

**Comment by santoja** [comment]
Tambem gostaria de saber, quero contribuir

**Comment by prhost** [comment]
Pelo visto não. Criar um fork e começar outro.

**Comment by caiquearaujo** [comment]
Sim, está sendo mantido @paulovitorbal, não está abandonado. Apenas não houve tanta necessidade de mudanças.

**Comment by paulovitorbal** [comment]
De qualquer forma, @caiquearaujo, estou a disposição para ajudar.

Um abraço, parabéns pelo ótimo trabalho.

**Comment by caiquearaujo** [comment]
Estamos aberto a pull requests @paulovitorbal, é só dar uma olhada nas regras de contribuição! 😆
