### ISSUE TITLE
plugins para Bagisto

### ISSUE THREAD

**Issue by marcelowu** [piggly-dev/php-pix#4]
possivel ou pretende fazer um plugins para Bagisto ? A Free and Opensource Laravel eCommerce.
https://github.com/bagisto/bagisto
https://devdocs.bagisto.com/1.x/advanced/create_payment_method.html#_1-by-using-bagisto-package-generator

**Comment by caiquearaujo** [comment]
No caso, a essa biblioteca aqui só compete a criação e manipulação dos códigos pix. Também desenvolvemos, claro, o plugin para Woocommerce, mas sem previsão para desenvolvimento em outras plataformas.
