### ISSUE TITLE
QRCode não reconhecido pelo app do Inter

### ISSUE THREAD

**Issue by leoneparise** [piggly-dev/php-pix#5]
Boa noite,

O app do banco inter não consegue ler o QRCode abaixo:

<img width="565" alt="Screen Shot 2021-05-25 at 21 41 58" src="https://user-images.githubusercontent.com/1442927/119585963-349d2e80-bda2-11eb-908c-e6fae3e902e2.png">

Segue também o PIX Code:

```
00020101021126330014br.gov.bcb.pix0111002051041185204000053039865406350.005802BR5928Leone Parise Vieira da Silva6006Maceió62070503***6304E5FB
```

Seria um problema com o app ou com o QR Code? Outros apps como BB e Nubank conseguem ler perfeitamente.

**Comment by caiquearaujo** [comment]
@leoneparise remova os acentos ao gerar o código Pix, por exemplo, em "Maceió" e opte por utilizar um identificador diferente de "***"! Isso deve resolver os problemas de incompatibilidade.

Dependendo de como você estiver utilizando a biblioteca, recomendo que utilize os modificadores no Payload:

- `applyValidCharacters()` (alguns Bancos/PSPs não leem acentuações no Pix) determina a substituição dos acentos e demais caracteres inválidos como [\!\.\,\@\#\$\%\&\*\(\)\/\*\?]. Esse modificador é aplicado nos campos `description`, `merchantName` e `merchantCity`;

E force a definição de um identificador, mesmo que aleatório.

**Comment by leoneparise** [comment]
Muito Obrigado @caiquearaujo pela explicação. Achei que o método `applyValidCharacters()` já era aplicado ao nome da cidade quando chamamos o `setMerchantCity()`

**Comment by leoneparise** [comment]
Vou fechar a issue já que não é um problema na biblioteca.

**Comment by caiquearaujo** [comment]
A gente está preparando a versão 2 dessa biblioteca que fará todas as correções automaticamente, incluindo todo o suporte a versão mais recente do Pix.
